## MATH 440 Binomial Trees  
### January 25, 2025

In [1]:
import numpy as np

In [2]:
def P_S(S_0,p_u,u,d,T):
    S_Matrix=np.zeros((T+1,T+1),dtype=float)
    P_Matrix=np.zeros((T+1,T+1),dtype=float)
    S_Matrix[0][0]=S_0
    P_Matrix[0][0]=1
    
    for t in range(1,T+1):
        for row in range(t+1):
            if row == t:
                S_Matrix[row][t]=d*S_Matrix[row-1][t-1]
                P_Matrix[row][t]=(1-p_u)*P_Matrix[row-1][t-1]
            else:
                S_Matrix[row][t]=u*S_Matrix[row][t-1]
                P_Matrix[row][t]=(p_u*P_Matrix[row][t-1]+(1-p_u)*P_Matrix[row-1][t-1])
    
    return S_Matrix, P_Matrix

In [15]:
def V(S_0,S_Matrix,r,c,p_u,u,d,T):
    V_Matrix=np.zeros((T+1,T+1),dtype=float)
    Z_Matrix=np.zeros((T+1,T+1),dtype=float)

    for t in range(T+1):
        for row in range(t+1):
            Z_Matrix[row][t]=np.exp(-r*t)*(S_Matrix[row][t]-c)
            V_Matrix[:,T]=Z_Matrix[:,T]
            
    for t in range(T-1,-1,-1):
        for row in range(t+1):
            Expected_future_V=(p_u*V_Matrix[row,t+1]+(1-p_u)*V_Matrix[row+1,t+1])
            V_Matrix[row, t]=max(Z_Matrix[row,t],Expected_future_V)

    return Z_Matrix, V_Matrix

In [17]:
S_0=100
T=5
r=0.05
c=10
p_u=0.49 #np.random.uniform(0,1)
u=1.003
d=0.997

S_Matrix,P_Matrix=P_S(S_0,p_u,u,d,T)
Z_Matrix,V_Matrix=V(S_0,S_Matrix,r,c,p_u,u,d,T)

print("S_Matrix: \n",S_Matrix)
#print("Z_Matrix: \n",Z_Matrix)
print("V_Matrix: \n",V_Matrix)
print("P_Matrix: \n",P_Matrix)

S_Matrix: 
 [[100.         100.3        100.6009     100.9027027  101.20541081
  101.50902704]
 [  0.          99.7         99.9991     100.2990973  100.59999459
  100.90179458]
 [  0.           0.          99.4009      99.6991027   99.99820001
  100.29819461]
 [  0.           0.           0.          99.1026973   99.40000539
   99.69820541]
 [  0.           0.           0.           0.          98.80538921
   99.10180538]
 [  0.           0.           0.           0.           0.
   98.50897304]]
V_Matrix: 
 [[90.         85.89601703 81.97908443 78.24068129 74.67267468 71.26730192]
 [ 0.         85.32527938 81.43455327 77.72115331 74.1770018  70.7943888 ]
 [ 0.          0.         80.89327953 77.20473317 73.68429407 70.32430467]
 [ 0.          0.          0.         76.69140229 73.19453374 69.85703261]
 [ 0.          0.          0.          0.         72.70770318 69.3925558 ]
 [ 0.          0.          0.          0.          0.         68.93085751]]
P_Matrix: 
 [[1.         0.49     